# Init wallpaper
exec-once = swww-daemon
exec-once = ~/.config/hypr/scripts/start-wallpaper.sh

# Init widgets of quickshell
<<<<<<< HEAD
exec-once = ~/.config/hypr/scripts/start-shell.sh
=======
exec-once = /home/ferreira-gn/.config/hypr/scripts/start-shell.sh
>>>>>>> 7739b3e98737995f4e080421e0f1458382b3af12
