# Init lockscreen background
exec-once = hypridle

# Init wallpaper
exec-once = awww-daemon
exec-once = ~/.config/hypr/scripts/start-wallpaper.sh

# Init widgets of quickshell
exec-once = ~/.config/hypr/scripts/start-shell.sh

