monitor=,preferred,auto,1

# variaveis de ambiente com os links do quickshell
env = QT_QPA_PLATFORM,wayland
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1

source = ./general.conf
source = ./keybinds.conf
source = ./input.conf
source = ./decoration.conf
source = ./colors.conf
source = ./misc.conf

# source = ./gestures.conf
# source = ./animations.conf

source = ./execs.conf
