
# ----------------------------
# Variáveis base
# ----------------------------
$mod = SUPER
$terminal = kitty
$terminalSecundary = alacritty
$launcher = wofi --show drun
$browser = brave
$zed = zeditor


# ----------------------------
# Aplicações essenciais
# ----------------------------
bind = $mod, Return, exec, $terminal
bind = $mod, T, exec, $terminalSecundary
bind = $mod, K, exec, $launcher
bind = $mod, W, exec, $browser
bind = $mod, Z, exec, $zed
bind = $mod, Q, killactive
bind = $mod SHIFT, E, exit

# ----------------------------
# Gerenciamento de janelas
# ----------------------------
bind = $mod, F, fullscreen
bind = $mod, Space, togglefloating
bind = $mod, P, pseudo
bind = $mod, J, togglesplit

# ----------------------------
# Foco entre janelas (hjkl-style)
# ----------------------------
bind = $mod, H, movefocus, l
bind = $mod, Ç, movefocus, r
bind = $mod, G, movefocus, u
bind = $mod, J, movefocus, d

# ----------------------------
# Mover janelas
# ----------------------------
bind = $mod SHIFT, H, movewindow, l
bind = $mod SHIFT, L, movewindow, r
bind = $mod SHIFT, K, movewindow, u
bind = $mod SHIFT, J, movewindow, d

# ----------------------------
# Workspaces (1–9)
# ----------------------------
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9

# ----------------------------
# Mover janela para workspace
# ----------------------------
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9

# ----------------------------
# Alternar entre os workspace
# ----------------------------
bind = $mod, right, exec, sh -c 'hyprctl dispatch workspace $(( $(hyprctl activeworkspace -j | jq .id) + 1 ))' , silent
bind = $mod, left, exec, sh -c 'hyprctl dispatch workspace $(( $(hyprctl activeworkspace -j | jq .id) - 1 ))'

# ----------------------------
# Scroll para trocar workspace
# ----------------------------
bind = $mod, mouse_down, workspace, e+1
bind = $mod, mouse_up, workspace, e-1

# ----------------------------
# Mouse (mover / redimensionar)
# ----------------------------
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow


# ----------------------------
# Gerenciamento do volume (diminuir / aumentar / mute)
# ----------------------------
bind  = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
binde = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
binde = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+


# ----------------------------
# Captura de tela
# ----------------------------
bind = , Print, exec, sh -c 'hyprshot -m region --freeze --raw  | satty -f - --output-filename "/home/ferreira-gn/Images/ScreenShots/screenshot-$(date +%Y-%m-%d_%H-%M-%S).png"'



# ----------------------------
# Brilho da tela
# ----------------------------
binde = , XF86MonBrightnessUp, exec, brightnessctl set +5%
binde = , XF86MonBrightnessDown, exec, brightnessctl set 5%-


# ----------------------------
# Wallpaper
# ----------------------------
bind = $mod SHIFT, W, exec, sh -c ~/.config/hypr/scripts/switch-wallpaper.sh


# ----------------------------
# LockScreen
# ----------------------------
bind = $mod, L, exec, hyprlock